- name: Update packages
  #Debian
  apt:
    update_cache: yes
    upgrade: yes

  #Fedora  
  #dnf:
  #name: "*"
  #state: latest

- name: Install essential packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    #validate: "usr/sbin/visudo -cf %s"

#- name: Change ssh port to {{ port }}
#  set_fact:
#    ansible_port: {{ port }}

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed